*** Variables ***
${burgur_menu.btn_burgur}             xpath=//div[@class="${burgur_menu.lbl_open_menu}"]
${burgur_menu.btn_close_burgur}       xpath=//button[text()="${burgur_menu.lbl_close_menu}"]
${burgur_menu.btn_all_items}          xpath=//a[text()="${burgur_menu.lbl_all_items}"]
${burgur_menu.btn_about}              xpath=//a[text()="${burgur_menu.lbl_about}"]
${burgur_menu.btn_logout}             xpath=//a[text()="${burgur_menu.lbl_logout}"]
${burgur_menu.btn_reset_app_state}    xpath=//a[text()="${burgur_menu.lbl_reset_app_state}"]
